#!/usr/bin/env python3
"""Extract the maze-evil INDEX8 texture arrays into a plain C source file.

Usage:
    python3 extract_textures.py \
        /path/to/micropixel/guest/apps/maze-evil/gfx/textures.cpp \
        assets.c

The generated file is checked in; rerun only when the source artwork changes.
"""
import re
import sys

ORDER = [
    "Brick", "Stone", "Tech", "Flesh", "Wood", "Door", "Exit",
    "Floor", "Ceiling",
]


def parse_arrays(path):
    text = open(path, encoding="utf-8").read()
    found = {}
    for match in re.finditer(r"constexpr Texture k(\w+) = \{(.*?)\};", text, re.S):
        name = match.group(1)
        values = [int(v) for v in re.findall(r"\d+", match.group(2))]
        found[name] = values
    return found


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    arrays = parse_arrays(sys.argv[1])
    out = []
    out.append("/* Generated by extract_textures.py from maze-evil gfx/textures.cpp. */\n")
    out.append('#include "assets.h"\n\n')
    out.append("const uint8_t kTextureData[TEX_COUNT][TEX_SIZE * TEX_SIZE] = {\n")
    for name in ORDER:
        values = arrays[name]
        assert len(values) == 128 * 128, (name, len(values))
        out.append("    { /* %s */\n" % name)
        for start in range(0, len(values), 16):
            row = ", ".join(str(v) for v in values[start:start + 16])
            out.append("        %s,\n" % row)
        out.append("    },\n")
    out.append("};\n\n")
    out.append("const texture_t kTextures[TEX_COUNT] = {\n")
    for index, name in enumerate(ORDER):
        out.append("    {kTextureData[TEX_%s], TEX_SIZE, TEX_SHIFT}, /* %s */\n" %
                   (name.upper(), name))
    out.append("};\n")
    open(sys.argv[2], "w", encoding="utf-8").write("".join(out))


if __name__ == "__main__":
    main()
