#ifndef JUMP3D_FONT_H
#define JUMP3D_FONT_H

#include <stdint.h>

#include "pxa_raster.h"

/* INDEX8 glyph atlases generated by tools/generate_fonts.py. Each tier is
 * designed for a render-target height class and drawn at scale 1, so text is
 * never resampled by a fractional factor: compact for a half-resolution
 * target, standard for 296x240, large for bigger panels. */
#define J3_FONT_BIG 0u
#define J3_FONT_SMALL 1u
#define J3_FONT_CJK 2u
#define J3_FONT_FACES 3u

/* Texture slots: three faces per tier, then the shadow shapes. */
#define J3_FONT_SLOT_BASE 0u

/* Upper bound on one glyph atlas in bytes. The renderer's upload scratch is
 * sized from this, and jump3d_font.c fails to compile when generated data
 * exceeds it. */
#define J3_FONT_MAX_ATLAS_BYTES UINT32_C(32768)

typedef struct {
    const uint8_t *pixels;
    const char *glyphs; /* UTF-8 glyph string, one entry per cell */
    uint16_t cell_width;
    uint16_t cell_height;
    uint16_t columns; /* glyph cells per atlas row */
    uint16_t atlas_width;
    uint16_t atlas_height;
} j3_font_face_t;

/* Selects the tier used by every face (0 compact, 1 standard, 2 large). */
void j3_font_set_tier(uint8_t tier);
uint8_t j3_font_tier(void);

/* Uploads every tier's atlases into texture slots 0..8. `scratch` must hold
 * the largest atlas plus the upload header. */
int j3_font_upload(uint32_t context, uint8_t *scratch, uint32_t scratch_capacity);

/* Height of the selected tier's cell for `font`, in pixels. */
float j3_font_cell_height(uint8_t font);

/* Pixel width of `text` when drawn at `scale`. */
int j3_font_width(uint8_t font, int scale, const char *text);

/* How a glyph's coverage reaches the screen. RAMP indexes a palette block of
 * pre-blended colours (exact over the background it was built for, no per-pixel
 * arithmetic), ALPHA blends the ink with whatever is already there, and CRISP
 * is the binary cut-out used when the Host advertises neither path. */
typedef enum {
    J3_FONT_CRISP = 0u,
    J3_FONT_RAMP = 1u,
    J3_FONT_ALPHA = 2u
} j3_font_mode_t;

/* Draws `text` with its top-left corner at (x, y). `mode` picks the coverage
 * path and `ramp_base` names the palette block for J3_FONT_RAMP. */
void j3_font_draw(pxa_raster_draw_list_t *list, uint32_t capabilities,
                  uint8_t font, int x, int y, int scale, const char *text,
                  uint16_t color, uint8_t mode, uint8_t ramp_base);

#endif
