#!/usr/bin/env python3
"""Extract maze-evil INDEX8 textures and sprites into plain C sources.

Usage:
    python3 extract_assets.py \
        /path/to/maze-evil/gfx/textures.cpp \
        /path/to/maze-evil/gfx/sprites.cpp \
        <output-dir>

Writes assets.c (textures) and sprites.c (column-major padded sprites). The
generated files are checked in; rerun only when the source artwork changes.
"""
import os
import re
import sys

TEXTURE_ORDER = [
    "Brick", "Stone", "Tech", "Flesh", "Wood", "Door", "Exit",
    "Floor", "Ceiling",
]

SPRITE_ORDER = [
    "ImpWalkA", "ImpWalkB", "ImpAttack", "ImpPain", "ImpDead",
    "FireballA", "FireballB", "Medkit", "Ammo",
    "TorchA", "TorchB", "Barrel", "Shotgun", "MuzzleFlash",
    "TorchC", "TorchD",
]


def parse_arrays(path, pattern):
    text = open(path, encoding="utf-8").read()
    found = {}
    for match in re.finditer(pattern, text, re.S):
        values = [int(v) for v in re.findall(r"\d+", match.group(2))]
        found[match.group(1)] = values
    return found


def parse_sprite_table(path):
    text = open(path, encoding="utf-8").read()
    match = re.search(r"constexpr Sprite kSprites\[kSprCount\] = \{(.*?)\};",
                      text, re.S)
    if match is None:
        raise SystemExit("sprite table not found")
    table = []
    for entry in re.finditer(r"\{(\d+),\s*(\d+),\s*k(\w+)\}", match.group(1)):
        table.append((int(entry.group(1)), int(entry.group(2)),
                      entry.group(3)))
    return table


def pad_to_power_of_two(value):
    padded = 8
    while padded < value:
        padded <<= 1
    return padded


def write_textures(textures_path, out_dir):
    arrays = parse_arrays(textures_path,
                          r"constexpr Texture k(\w+) = \{(.*?)\};")
    lines = []
    lines.append("/* Generated by extract_assets.py from maze-evil textures.cpp. */\n")
    lines.append('#include "assets.h"\n\n')
    lines.append("const uint8_t kTextureData[TEX_COUNT][TEX_SIZE * TEX_SIZE] = {\n")
    for name in TEXTURE_ORDER:
        values = arrays[name]
        assert len(values) == 128 * 128, (name, len(values))
        lines.append("    { /* %s */\n" % name)
        for start in range(0, len(values), 16):
            lines.append("        %s,\n" %
                         ", ".join(str(v) for v in values[start:start + 16]))
        lines.append("    },\n")
    lines.append("};\n\n")
    lines.append("const texture_t kTextures[TEX_COUNT] = {\n")
    for index, name in enumerate(TEXTURE_ORDER):
        lines.append("    {kTextureData[TEX_%s], TEX_SIZE, TEX_SHIFT}, /* %s */\n"
                     % (name.upper(), name))
    lines.append("};\n")
    open(os.path.join(out_dir, "assets.c"), "w", encoding="utf-8").write(
        "".join(lines))


def write_sprites(sprites_path, out_dir):
    arrays = parse_arrays(sprites_path,
                          r"constexpr uint8_t k(\w+)\[\] = \{(.*?)\};")
    table = parse_sprite_table(sprites_path)
    assert len(table) == len(SPRITE_ORDER), len(table)
    lines = []
    lines.append("/* Generated by extract_assets.py from maze-evil sprites.cpp.\n")
    lines.append(" * Sprites are transposed to column-major and padded to a power of\n")
    lines.append(" * two on both axes with index 0, matching what maze-evil uploads. */\n")
    lines.append('#include "sprites.h"\n\n')
    descriptors = []
    for index, (width, height, name) in enumerate(table):
        assert name == SPRITE_ORDER[index], (name, SPRITE_ORDER[index])
        row_major = arrays[name]
        assert len(row_major) == width * height, (name, len(row_major))
        padded_w = pad_to_power_of_two(width)
        padded_h = pad_to_power_of_two(height)
        column_major = [0] * (padded_w * padded_h)
        for v in range(height):
            for u in range(width):
                column_major[u * padded_h + v] = row_major[v * width + u]
        lines.append("const uint8_t kSpr%s[%d * %d] = {\n" %
                     (name, padded_w, padded_h))
        for start in range(0, len(column_major), 16):
            lines.append("    %s,\n" % ", ".join(
                str(v) for v in column_major[start:start + 16]))
        lines.append("};\n\n")
        descriptors.append((name, width, height, padded_w, padded_h))
    lines.append("const sprite_t kSprites[SPR_COUNT] = {\n")
    for name, width, height, padded_w, padded_h in descriptors:
        lines.append("    {kSpr%s, %d, %d, %d, %d}, /* %s */\n" %
                     (name, width, height, padded_w, padded_h, name))
    lines.append("};\n")
    open(os.path.join(out_dir, "sprites.c"), "w", encoding="utf-8").write(
        "".join(lines))


def main():
    if len(sys.argv) != 4:
        raise SystemExit(__doc__)
    write_textures(sys.argv[1], sys.argv[3])
    write_sprites(sys.argv[2], sys.argv[3])


if __name__ == "__main__":
    main()
