#ifndef PXA_CLOCK_H
#define PXA_CLOCK_H

#include <stdint.h>

#define PXA_CLOCK_SERVICE_ID UINT16_C(4)
#define PXA_CLOCK_SERVICE_MAJOR UINT16_C(0)
#define PXA_CLOCK_SERVICE_MINOR UINT16_C(1)
#define PXA_CLOCK_SET_PERIOD UINT16_C(1)
#define PXA_CLOCK_NOW UINT16_C(2)
#define PXA_CLOCK_TICK UINT16_C(0x8001)
#define PXA_CLOCK_NOW_RESULT UINT16_C(0x8002)

#endif
