/* Generated by tools/generate_textures.py; do not edit. */
#ifndef TOMB_TEXTURES_H
#define TOMB_TEXTURES_H

#include <stdint.h>

#define TOMB_TEXTURE_SIZE 64u
#define TOMB_TEXTURE_COUNT 10u

/* Texture slot IDs, uploaded in this order. Level faces reference them by value. */
enum {
    TEX_WALL = 0,
    TEX_FLOOR = 1,
    TEX_CEILING = 2,
    TEX_CARVED = 3,
    TEX_MOSSY_WALL = 4,
    TEX_STEPS = 5,
    TEX_CLOTH = 6,
    TEX_FACE = 7,
    TEX_WATER = 8,
    TEX_BONE = 9,
};

const uint8_t *tomb_texture_texels(uint8_t slot);

#endif
