get_filename_component(_pxa_sdk_prefix "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
file(STRINGS "${_pxa_sdk_prefix}/VERSION" PxaGuest_VERSION LIMIT_COUNT 1)
set(PXA_CMAKE_MODULE_DIR "${CMAKE_CURRENT_LIST_DIR}")
if(NOT DEFINED PXA_GUEST_SDK_DIR)
    set(PXA_GUEST_SDK_DIR "${_pxa_sdk_prefix}/sdk/guest-c")
endif()
if(NOT DEFINED PXA_CPP_SDK_DIR)
    set(PXA_CPP_SDK_DIR "${_pxa_sdk_prefix}/sdk/guest-cpp")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/PxaGuest.cmake")
