#ifndef PXA_GAME_MUSIC_H
#define PXA_GAME_MUSIC_H

#include <stdint.h>

enum {
    PXA_GAME_SFX_THEME_BRICK = 0,
    PXA_GAME_SFX_THEME_GARDEN,
    PXA_GAME_SFX_THEME_FLAPPY,
    PXA_GAME_SFX_THEME_JUMPING,
    PXA_GAME_SFX_THEME_JUMP_JUMP,
    PXA_GAME_SFX_THEME_PLANE,
    PXA_GAME_SFX_THEME_TETRIS,
    PXA_GAME_SFX_THEME_COUNT,
};

typedef struct {
    uint16_t phase_step;
    uint8_t eighths;
} pxa_game_music_note_t;

enum {
    PXA_MUSIC_TIMBRE_PIANO = 0,
    PXA_MUSIC_TIMBRE_BASS,
    PXA_MUSIC_TIMBRE_SAX,
    PXA_MUSIC_TIMBRE_STRINGS,
    PXA_MUSIC_TIMBRE_PIZZICATO,
    PXA_MUSIC_TIMBRE_SINE,
    PXA_MUSIC_TIMBRE_LEAD,
    PXA_MUSIC_TIMBRE_KICK,
    PXA_MUSIC_TIMBRE_SNARE,
    PXA_MUSIC_TIMBRE_CLICK,
};

typedef struct {
    uint16_t start_eighth;
    uint16_t phase_step;
    uint8_t eighths;
    uint8_t gain;
    uint8_t timbre;
} pxa_game_music_event_t;

typedef struct {
    const pxa_game_music_note_t* melody;
    uint16_t melody_length;
    uint16_t bpm;
    uint16_t kick_pattern;
    uint16_t snare_pattern;
    uint16_t hat_pattern;
    uint16_t bass[8];
    const pxa_game_music_event_t* score;
    uint16_t score_length;
    uint16_t score_eighths;
} pxa_game_music_song_t;

#define PXA_MUSIC_REST 0u
#define PXA_MUSIC_C2 268u
#define PXA_MUSIC_D2 301u
#define PXA_MUSIC_E2 338u
#define PXA_MUSIC_F2 358u
#define PXA_MUSIC_FS2 379u
#define PXA_MUSIC_G2 401u
#define PXA_MUSIC_GS2 425u
#define PXA_MUSIC_A2 451u
#define PXA_MUSIC_B2 506u
#define PXA_MUSIC_B3 1011u
#define PXA_MUSIC_C3 536u
#define PXA_MUSIC_D3 601u
#define PXA_MUSIC_DS3 637u
#define PXA_MUSIC_E3 675u
#define PXA_MUSIC_F3 715u
#define PXA_MUSIC_FS3 758u
#define PXA_MUSIC_G3 803u
#define PXA_MUSIC_A3 901u
#define PXA_MUSIC_C4 1072u
#define PXA_MUSIC_D4 1203u
#define PXA_MUSIC_DS4 1274u
#define PXA_MUSIC_E4 1350u
#define PXA_MUSIC_F4 1430u
#define PXA_MUSIC_FS4 1515u
#define PXA_MUSIC_G4 1606u
#define PXA_MUSIC_GS4 1701u
#define PXA_MUSIC_A4 1802u
#define PXA_MUSIC_B4 2023u
#define PXA_MUSIC_C5 2143u
#define PXA_MUSIC_D5 2406u
#define PXA_MUSIC_DS5 2549u
#define PXA_MUSIC_E5 2700u
#define PXA_MUSIC_F5 2861u
#define PXA_MUSIC_FS5 3031u
#define PXA_MUSIC_G5 3211u
#define PXA_MUSIC_GS5 3402u
#define PXA_MUSIC_A5 3604u
#define PXA_MUSIC_B5 4046u
#define PXA_MUSIC_C6 4286u
#define PXA_MUSIC_D6 4811u
#define PXA_MUSIC_E6 5401u
#define PXA_MUSIC_F6 5722u
#define PXA_MUSIC_FS6 6062u
#define PXA_MUSIC_G6 6422u
#define PXA_MUSIC_A6 7209u

#define PXA_MUSIC_NOTE(pitch, duration) {pitch, duration}
#define PXA_MUSIC_EVENT(start, pitch, duration, amplitude, tone) \
    {start, pitch, duration, amplitude, tone}
#define PXA_MUSIC_LENGTH(notes) ((uint16_t)(sizeof(notes) / sizeof((notes)[0])))

/* Offenbach's Can-Can: a fast arcade arrangement for brick breaking. */
static const pxa_game_music_note_t pxa_game_music_brick[] = {
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_D5, 2), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_D5, 4), PXA_MUSIC_NOTE(PXA_MUSIC_REST, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_C5, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 4), PXA_MUSIC_NOTE(PXA_MUSIC_REST, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_D5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D5, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_E5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_FS5, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_G5, 2), PXA_MUSIC_NOTE(PXA_MUSIC_FS5, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_E5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D5, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 2), PXA_MUSIC_NOTE(PXA_MUSIC_REST, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D5, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_E5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_FS5, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_E5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D5, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 2), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_REST, 1), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D5, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_E5, 2), PXA_MUSIC_NOTE(PXA_MUSIC_D5, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_REST, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D5, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 6),
    PXA_MUSIC_NOTE(PXA_MUSIC_REST, 2),
};

/* Plants vs. Zombies "Grasswalk" MIDI, all non-percussion instrument tracks. */
static const pxa_game_music_note_t pxa_game_music_garden[] = {
    PXA_MUSIC_NOTE(PXA_MUSIC_REST, 1),
};

static const pxa_game_music_event_t pxa_game_music_garden_score[] = {
    PXA_MUSIC_EVENT(0, PXA_MUSIC_A2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(2, PXA_MUSIC_DS4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(2, PXA_MUSIC_E3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(3, PXA_MUSIC_E4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(3, PXA_MUSIC_A3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(4, PXA_MUSIC_A4, 2, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(6, PXA_MUSIC_E2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(8, PXA_MUSIC_A2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(10, PXA_MUSIC_DS4, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(10, PXA_MUSIC_E3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(11, PXA_MUSIC_E4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(11, PXA_MUSIC_A3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(12, PXA_MUSIC_G4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(13, PXA_MUSIC_FS4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(14, PXA_MUSIC_F4, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(14, PXA_MUSIC_E2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(15, PXA_MUSIC_E4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(16, PXA_MUSIC_DS4, 4, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(16, PXA_MUSIC_F2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(16, PXA_MUSIC_A5, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(17, PXA_MUSIC_GS5, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(18, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(18, PXA_MUSIC_DS5, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(19, PXA_MUSIC_G5, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(20, PXA_MUSIC_F3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(20, PXA_MUSIC_FS5, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(21, PXA_MUSIC_D5, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(22, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(22, PXA_MUSIC_F5, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(23, PXA_MUSIC_E5, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(24, PXA_MUSIC_F2, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(24, PXA_MUSIC_C5, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(28, PXA_MUSIC_F2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(29, PXA_MUSIC_FS2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(30, PXA_MUSIC_G2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(31, PXA_MUSIC_GS2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(32, PXA_MUSIC_A2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(32, PXA_MUSIC_A2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(32, PXA_MUSIC_A4, 8, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(32, PXA_MUSIC_E5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(34, PXA_MUSIC_DS4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(34, PXA_MUSIC_E3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(35, PXA_MUSIC_E4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(35, PXA_MUSIC_A3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(36, PXA_MUSIC_A4, 2, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(38, PXA_MUSIC_E2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(40, PXA_MUSIC_A2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(40, PXA_MUSIC_E4, 8, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(40, PXA_MUSIC_C5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(42, PXA_MUSIC_DS4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(42, PXA_MUSIC_E3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(43, PXA_MUSIC_E4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(43, PXA_MUSIC_A3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(44, PXA_MUSIC_G4, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(45, PXA_MUSIC_FS4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(46, PXA_MUSIC_F4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(46, PXA_MUSIC_E2, 2, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(47, PXA_MUSIC_E4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(48, PXA_MUSIC_DS4, 4, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(48, PXA_MUSIC_F2, 2, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(48, PXA_MUSIC_A5, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(48, PXA_MUSIC_A4, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(48, PXA_MUSIC_DS5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(49, PXA_MUSIC_GS5, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(50, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(50, PXA_MUSIC_DS5, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(51, PXA_MUSIC_G5, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(52, PXA_MUSIC_F3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(52, PXA_MUSIC_C3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(52, PXA_MUSIC_FS5, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(53, PXA_MUSIC_D5, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(54, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(54, PXA_MUSIC_E2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(54, PXA_MUSIC_F5, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(55, PXA_MUSIC_E5, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(56, PXA_MUSIC_F2, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(56, PXA_MUSIC_F2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(56, PXA_MUSIC_C5, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(61, PXA_MUSIC_F3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(62, PXA_MUSIC_E3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(63, PXA_MUSIC_DS3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(64, PXA_MUSIC_D4, 4, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(64, PXA_MUSIC_D2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(64, PXA_MUSIC_D3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(64, PXA_MUSIC_A5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(66, PXA_MUSIC_A2, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(68, PXA_MUSIC_D3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(70, PXA_MUSIC_E4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(70, PXA_MUSIC_A2, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(71, PXA_MUSIC_F4, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(72, PXA_MUSIC_E4, 2, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(72, PXA_MUSIC_E2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(72, PXA_MUSIC_GS5, 4, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(74, PXA_MUSIC_B3, 2, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(74, PXA_MUSIC_B2, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(76, PXA_MUSIC_E4, 2, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(76, PXA_MUSIC_E3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(76, PXA_MUSIC_B5, 4, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(77, PXA_MUSIC_E3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(78, PXA_MUSIC_D4, 2, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(78, PXA_MUSIC_B2, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(78, PXA_MUSIC_D3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(79, PXA_MUSIC_B2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(80, PXA_MUSIC_C4, 4, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(80, PXA_MUSIC_A2, 2, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(80, PXA_MUSIC_C3, 4, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(80, PXA_MUSIC_G5, 4, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(80, PXA_MUSIC_C6, 8, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(82, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(82, PXA_MUSIC_E3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(84, PXA_MUSIC_E4, 4, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(84, PXA_MUSIC_G2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(84, PXA_MUSIC_B2, 4, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(84, PXA_MUSIC_E5, 4, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(86, PXA_MUSIC_B2, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(86, PXA_MUSIC_D3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(88, PXA_MUSIC_A4, 4, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(88, PXA_MUSIC_D2, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(88, PXA_MUSIC_A2, 4, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(88, PXA_MUSIC_D5, 4, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(88, PXA_MUSIC_D6, 4, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(90, PXA_MUSIC_A2, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(92, PXA_MUSIC_D2, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(94, PXA_MUSIC_A2, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(96, PXA_MUSIC_A4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(96, PXA_MUSIC_F2, 3, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(96, PXA_MUSIC_A4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(97, PXA_MUSIC_GS4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(97, PXA_MUSIC_GS4, 1, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(98, PXA_MUSIC_A4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(98, PXA_MUSIC_A4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(99, PXA_MUSIC_B4, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(99, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(99, PXA_MUSIC_B4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(100, PXA_MUSIC_C5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(100, PXA_MUSIC_F3, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(100, PXA_MUSIC_C5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(102, PXA_MUSIC_C2, 2, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(104, PXA_MUSIC_A4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(104, PXA_MUSIC_D2, 3, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(104, PXA_MUSIC_A4, 1, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(105, PXA_MUSIC_GS4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(105, PXA_MUSIC_GS4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(106, PXA_MUSIC_A4, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(106, PXA_MUSIC_A4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(107, PXA_MUSIC_B4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(107, PXA_MUSIC_A2, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(107, PXA_MUSIC_B4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(108, PXA_MUSIC_C5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(108, PXA_MUSIC_D3, 2, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(108, PXA_MUSIC_C5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(110, PXA_MUSIC_D5, 2, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(110, PXA_MUSIC_D2, 2, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(110, PXA_MUSIC_D5, 2, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(112, PXA_MUSIC_B4, 2, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(112, PXA_MUSIC_E2, 2, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(112, PXA_MUSIC_B2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(112, PXA_MUSIC_B4, 12, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(116, PXA_MUSIC_E5, 4, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(120, PXA_MUSIC_GS5, 2, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(124, PXA_MUSIC_B5, 2, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(126, PXA_MUSIC_E6, 2, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(128, PXA_MUSIC_A6, 2, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(128, PXA_MUSIC_A2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(128, PXA_MUSIC_A4, 3, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(128, PXA_MUSIC_C5, 16, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(128, PXA_MUSIC_C6, 16, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(130, PXA_MUSIC_G6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(130, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(130, PXA_MUSIC_E3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(131, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(131, PXA_MUSIC_B4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(132, PXA_MUSIC_FS6, 2, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(132, PXA_MUSIC_E2, 2, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(132, PXA_MUSIC_C5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(133, PXA_MUSIC_E4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(134, PXA_MUSIC_FS6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(134, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(134, PXA_MUSIC_E3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(134, PXA_MUSIC_C5, 1, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(135, PXA_MUSIC_D6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(135, PXA_MUSIC_B4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(136, PXA_MUSIC_F6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(136, PXA_MUSIC_A2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(136, PXA_MUSIC_A4, 3, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(137, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(138, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(138, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(138, PXA_MUSIC_E3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(139, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(139, PXA_MUSIC_B4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(140, PXA_MUSIC_C6, 2, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(140, PXA_MUSIC_E2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(140, PXA_MUSIC_C5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(141, PXA_MUSIC_D5, 1, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(142, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(142, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(142, PXA_MUSIC_E3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(142, PXA_MUSIC_C5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(143, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(143, PXA_MUSIC_B4, 1, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(144, PXA_MUSIC_A5, 4, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(144, PXA_MUSIC_F2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(144, PXA_MUSIC_A4, 3, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(144, PXA_MUSIC_F4, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(144, PXA_MUSIC_F5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(146, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(146, PXA_MUSIC_F3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(147, PXA_MUSIC_B4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(148, PXA_MUSIC_C2, 2, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(148, PXA_MUSIC_C5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(149, PXA_MUSIC_E4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(150, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(150, PXA_MUSIC_F3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(150, PXA_MUSIC_C5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(151, PXA_MUSIC_B4, 1, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(152, PXA_MUSIC_F2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(152, PXA_MUSIC_A4, 4, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(152, PXA_MUSIC_G4, 4, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(152, PXA_MUSIC_G5, 4, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(154, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(154, PXA_MUSIC_F3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(156, PXA_MUSIC_G2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(156, PXA_MUSIC_B4, 4, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(156, PXA_MUSIC_A4, 4, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(156, PXA_MUSIC_A5, 4, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(158, PXA_MUSIC_D3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(158, PXA_MUSIC_G3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(160, PXA_MUSIC_A6, 2, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(160, PXA_MUSIC_A2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(160, PXA_MUSIC_A4, 3, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(160, PXA_MUSIC_C5, 16, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(160, PXA_MUSIC_C6, 16, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(162, PXA_MUSIC_G6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(162, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(162, PXA_MUSIC_E3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(163, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(163, PXA_MUSIC_B4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(164, PXA_MUSIC_FS6, 2, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(164, PXA_MUSIC_E2, 2, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(164, PXA_MUSIC_C5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(165, PXA_MUSIC_E4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(166, PXA_MUSIC_FS6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(166, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(166, PXA_MUSIC_E3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(166, PXA_MUSIC_C5, 1, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(167, PXA_MUSIC_D6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(167, PXA_MUSIC_B4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(168, PXA_MUSIC_F6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(168, PXA_MUSIC_A2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(168, PXA_MUSIC_A4, 3, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(169, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(170, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(170, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(170, PXA_MUSIC_E3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(171, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(171, PXA_MUSIC_B4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(172, PXA_MUSIC_C6, 2, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(172, PXA_MUSIC_E2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(172, PXA_MUSIC_C5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(173, PXA_MUSIC_D5, 1, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(174, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(174, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(174, PXA_MUSIC_E3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(174, PXA_MUSIC_C5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(175, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(175, PXA_MUSIC_B4, 1, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(176, PXA_MUSIC_A5, 4, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(176, PXA_MUSIC_F2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(176, PXA_MUSIC_A4, 3, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(176, PXA_MUSIC_F4, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(176, PXA_MUSIC_F5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(178, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(178, PXA_MUSIC_F3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(179, PXA_MUSIC_B4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(180, PXA_MUSIC_C2, 2, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(180, PXA_MUSIC_C5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(181, PXA_MUSIC_E4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(182, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(182, PXA_MUSIC_F3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(182, PXA_MUSIC_C5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(183, PXA_MUSIC_B4, 1, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(184, PXA_MUSIC_F2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(184, PXA_MUSIC_A4, 4, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(184, PXA_MUSIC_G4, 4, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(184, PXA_MUSIC_G5, 4, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(186, PXA_MUSIC_C3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(186, PXA_MUSIC_F3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(188, PXA_MUSIC_G2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(188, PXA_MUSIC_G4, 4, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(188, PXA_MUSIC_A4, 4, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(188, PXA_MUSIC_A5, 4, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(190, PXA_MUSIC_D3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(190, PXA_MUSIC_G3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(192, PXA_MUSIC_A2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(192, PXA_MUSIC_A4, 8, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(195, PXA_MUSIC_E3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(196, PXA_MUSIC_A3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(198, PXA_MUSIC_E2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(200, PXA_MUSIC_A2, 2, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(204, PXA_MUSIC_F2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(205, PXA_MUSIC_FS2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(206, PXA_MUSIC_G2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(207, PXA_MUSIC_GS2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(208, PXA_MUSIC_A2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(208, PXA_MUSIC_A2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(208, PXA_MUSIC_A5, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(210, PXA_MUSIC_GS5, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(211, PXA_MUSIC_E3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(211, PXA_MUSIC_E5, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(212, PXA_MUSIC_A3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(212, PXA_MUSIC_G5, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(214, PXA_MUSIC_E2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(214, PXA_MUSIC_F5, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(216, PXA_MUSIC_A2, 2, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(216, PXA_MUSIC_E5, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(220, PXA_MUSIC_F2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(221, PXA_MUSIC_FS2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(222, PXA_MUSIC_G2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(223, PXA_MUSIC_GS2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(224, PXA_MUSIC_A2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(224, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(226, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(228, PXA_MUSIC_E2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(228, PXA_MUSIC_E3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(230, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(232, PXA_MUSIC_A2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(232, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(233, PXA_MUSIC_GS2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(234, PXA_MUSIC_A2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(234, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(235, PXA_MUSIC_C3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(236, PXA_MUSIC_E2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(236, PXA_MUSIC_E3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(238, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(240, PXA_MUSIC_A2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(240, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(241, PXA_MUSIC_GS2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(242, PXA_MUSIC_A2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(242, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(243, PXA_MUSIC_B2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(244, PXA_MUSIC_C3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(244, PXA_MUSIC_G3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(246, PXA_MUSIC_E3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(246, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(248, PXA_MUSIC_D3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(248, PXA_MUSIC_D4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(250, PXA_MUSIC_C3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(250, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(252, PXA_MUSIC_B2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(252, PXA_MUSIC_B3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(254, PXA_MUSIC_B3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(256, PXA_MUSIC_A2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(256, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(258, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(260, PXA_MUSIC_G2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(260, PXA_MUSIC_B3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(262, PXA_MUSIC_D4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(264, PXA_MUSIC_C3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(264, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(265, PXA_MUSIC_B2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(266, PXA_MUSIC_C3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(266, PXA_MUSIC_E4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(267, PXA_MUSIC_E3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(268, PXA_MUSIC_F3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(268, PXA_MUSIC_F4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(270, PXA_MUSIC_D4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(272, PXA_MUSIC_E3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(272, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(274, PXA_MUSIC_C3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(274, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(275, PXA_MUSIC_A2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(276, PXA_MUSIC_B2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(276, PXA_MUSIC_E4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(278, PXA_MUSIC_C3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(278, PXA_MUSIC_GS4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(280, PXA_MUSIC_A2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(280, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(282, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(284, PXA_MUSIC_E4, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(285, PXA_MUSIC_D4, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(286, PXA_MUSIC_C4, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(287, PXA_MUSIC_B3, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(288, PXA_MUSIC_A2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(288, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(288, PXA_MUSIC_A5, 2, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(290, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(290, PXA_MUSIC_C6, 2, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(292, PXA_MUSIC_E2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(292, PXA_MUSIC_E3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(292, PXA_MUSIC_E5, 4, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(294, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(296, PXA_MUSIC_A2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(296, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(296, PXA_MUSIC_A5, 2, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(297, PXA_MUSIC_GS2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(298, PXA_MUSIC_A2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(298, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(298, PXA_MUSIC_C6, 2, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(299, PXA_MUSIC_C3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(300, PXA_MUSIC_E2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(300, PXA_MUSIC_E3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(300, PXA_MUSIC_E5, 4, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(302, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(304, PXA_MUSIC_A2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(304, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(304, PXA_MUSIC_C5, 4, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(304, PXA_MUSIC_C6, 8, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(305, PXA_MUSIC_GS2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(306, PXA_MUSIC_A2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(306, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(307, PXA_MUSIC_B2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(308, PXA_MUSIC_C3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(308, PXA_MUSIC_G3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(308, PXA_MUSIC_D5, 4, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(310, PXA_MUSIC_E3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(310, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(312, PXA_MUSIC_D3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(312, PXA_MUSIC_D4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(312, PXA_MUSIC_D6, 2, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(314, PXA_MUSIC_C3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(314, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(314, PXA_MUSIC_C6, 2, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(316, PXA_MUSIC_B2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(316, PXA_MUSIC_B3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(316, PXA_MUSIC_B5, 2, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(318, PXA_MUSIC_B3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(320, PXA_MUSIC_A2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(320, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(320, PXA_MUSIC_A5, 4, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(322, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(324, PXA_MUSIC_G2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(324, PXA_MUSIC_B3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(324, PXA_MUSIC_B5, 2, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(326, PXA_MUSIC_D4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(326, PXA_MUSIC_G5, 2, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(328, PXA_MUSIC_C3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(328, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(328, PXA_MUSIC_C6, 4, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(329, PXA_MUSIC_B2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(330, PXA_MUSIC_C3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(330, PXA_MUSIC_E4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(331, PXA_MUSIC_E3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(332, PXA_MUSIC_F3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(332, PXA_MUSIC_F4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(332, PXA_MUSIC_D6, 2, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(334, PXA_MUSIC_D4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(334, PXA_MUSIC_F6, 2, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(336, PXA_MUSIC_E3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(336, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(336, PXA_MUSIC_E6, 12, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(338, PXA_MUSIC_C3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(338, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(339, PXA_MUSIC_A2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(340, PXA_MUSIC_B2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(340, PXA_MUSIC_E4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(342, PXA_MUSIC_C3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(342, PXA_MUSIC_GS4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(344, PXA_MUSIC_A2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(344, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(346, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(348, PXA_MUSIC_E4, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(349, PXA_MUSIC_D4, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(350, PXA_MUSIC_C4, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(351, PXA_MUSIC_B3, 1, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(352, PXA_MUSIC_E4, 2, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(352, PXA_MUSIC_A2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(352, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(352, PXA_MUSIC_A5, 2, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(354, PXA_MUSIC_A4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(354, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(354, PXA_MUSIC_C6, 2, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(355, PXA_MUSIC_C5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(356, PXA_MUSIC_E5, 2, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(356, PXA_MUSIC_E2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(356, PXA_MUSIC_E3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(356, PXA_MUSIC_E5, 4, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(358, PXA_MUSIC_F5, 2, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(358, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(360, PXA_MUSIC_E5, 2, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(360, PXA_MUSIC_A2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(360, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(360, PXA_MUSIC_A5, 2, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(361, PXA_MUSIC_GS2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(362, PXA_MUSIC_E5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(362, PXA_MUSIC_A2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(362, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(362, PXA_MUSIC_C6, 2, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(363, PXA_MUSIC_C5, 1, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(363, PXA_MUSIC_C3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(364, PXA_MUSIC_A4, 2, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(364, PXA_MUSIC_E2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(364, PXA_MUSIC_E3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(364, PXA_MUSIC_E5, 4, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(366, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(367, PXA_MUSIC_A4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(368, PXA_MUSIC_A5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(368, PXA_MUSIC_A2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(368, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(368, PXA_MUSIC_C5, 4, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(368, PXA_MUSIC_C6, 8, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(369, PXA_MUSIC_GS5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(369, PXA_MUSIC_GS2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(370, PXA_MUSIC_E5, 2, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(370, PXA_MUSIC_A2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(370, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(371, PXA_MUSIC_B2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(372, PXA_MUSIC_G5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(372, PXA_MUSIC_C3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(372, PXA_MUSIC_G3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(372, PXA_MUSIC_D5, 4, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(373, PXA_MUSIC_E5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(374, PXA_MUSIC_C5, 2, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(374, PXA_MUSIC_E3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(374, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(376, PXA_MUSIC_D5, 1, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(376, PXA_MUSIC_D3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(376, PXA_MUSIC_D4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(376, PXA_MUSIC_D6, 2, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(377, PXA_MUSIC_A4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(378, PXA_MUSIC_D5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(378, PXA_MUSIC_C3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(378, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(378, PXA_MUSIC_C6, 2, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(379, PXA_MUSIC_C5, 1, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(380, PXA_MUSIC_B4, 3, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(380, PXA_MUSIC_B2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(380, PXA_MUSIC_B3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(380, PXA_MUSIC_B5, 2, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(382, PXA_MUSIC_B3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(384, PXA_MUSIC_DS4, 1, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(384, PXA_MUSIC_A2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(384, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(384, PXA_MUSIC_A5, 4, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(385, PXA_MUSIC_E4, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(386, PXA_MUSIC_A4, 2, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(386, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(388, PXA_MUSIC_G4, 2, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(388, PXA_MUSIC_G2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(388, PXA_MUSIC_B3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(388, PXA_MUSIC_B5, 2, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(390, PXA_MUSIC_F4, 2, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(390, PXA_MUSIC_D4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(390, PXA_MUSIC_G5, 2, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(392, PXA_MUSIC_E4, 2, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(392, PXA_MUSIC_C3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(392, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(392, PXA_MUSIC_C6, 4, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(393, PXA_MUSIC_B2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(394, PXA_MUSIC_A4, 2, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(394, PXA_MUSIC_C3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(394, PXA_MUSIC_E4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO),
    PXA_MUSIC_EVENT(395, PXA_MUSIC_E3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(396, PXA_MUSIC_C5, 2, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(396, PXA_MUSIC_F3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(396, PXA_MUSIC_F4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(396, PXA_MUSIC_D6, 2, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(398, PXA_MUSIC_D5, 2, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(398, PXA_MUSIC_D4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(398, PXA_MUSIC_F6, 2, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(400, PXA_MUSIC_E5, 8, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(400, PXA_MUSIC_E3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(400, PXA_MUSIC_A3, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(400, PXA_MUSIC_E6, 8, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(402, PXA_MUSIC_C3, 1, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(402, PXA_MUSIC_C4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(403, PXA_MUSIC_A2, 1, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(404, PXA_MUSIC_B2, 2, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(404, PXA_MUSIC_E4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(406, PXA_MUSIC_C3, 2, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(406, PXA_MUSIC_GS4, 2, 46, PXA_MUSIC_TIMBRE_PIZZICATO), PXA_MUSIC_EVENT(408, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(408, PXA_MUSIC_A4, 8, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(408, PXA_MUSIC_E5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(409, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(410, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(411, PXA_MUSIC_E5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(412, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(413, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(414, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(415, PXA_MUSIC_E5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(416, PXA_MUSIC_F6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(416, PXA_MUSIC_D5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(416, PXA_MUSIC_F5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(417, PXA_MUSIC_D6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(418, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(419, PXA_MUSIC_F5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(420, PXA_MUSIC_F6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(421, PXA_MUSIC_D6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(422, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(423, PXA_MUSIC_F5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(424, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(424, PXA_MUSIC_A4, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(424, PXA_MUSIC_E5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(425, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(426, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(427, PXA_MUSIC_E5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(428, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(429, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(430, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(431, PXA_MUSIC_E5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(432, PXA_MUSIC_F6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(432, PXA_MUSIC_D5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(432, PXA_MUSIC_F5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(433, PXA_MUSIC_D6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(434, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(435, PXA_MUSIC_F5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(436, PXA_MUSIC_F6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(437, PXA_MUSIC_D6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(438, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(439, PXA_MUSIC_F5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(440, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(440, PXA_MUSIC_A2, 8, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(440, PXA_MUSIC_A4, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(440, PXA_MUSIC_E5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(441, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(442, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(443, PXA_MUSIC_E5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(444, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(445, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(446, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(447, PXA_MUSIC_E5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(448, PXA_MUSIC_F6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(448, PXA_MUSIC_B2, 8, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(448, PXA_MUSIC_D5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(448, PXA_MUSIC_F5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(449, PXA_MUSIC_D6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(450, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(451, PXA_MUSIC_F5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(452, PXA_MUSIC_F6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(453, PXA_MUSIC_D6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(454, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(455, PXA_MUSIC_F5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(456, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(456, PXA_MUSIC_C3, 8, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(456, PXA_MUSIC_A4, 8, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(456, PXA_MUSIC_E5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(457, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(458, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(459, PXA_MUSIC_E5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(460, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(461, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(462, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(463, PXA_MUSIC_E5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(464, PXA_MUSIC_F6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(464, PXA_MUSIC_D3, 8, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(464, PXA_MUSIC_D5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(464, PXA_MUSIC_F5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(465, PXA_MUSIC_D6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(466, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(467, PXA_MUSIC_F5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(468, PXA_MUSIC_F6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(469, PXA_MUSIC_D6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(470, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(471, PXA_MUSIC_F5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(472, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(472, PXA_MUSIC_E4, 8, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(472, PXA_MUSIC_A2, 8, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(472, PXA_MUSIC_A4, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(472, PXA_MUSIC_E5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(473, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(474, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(475, PXA_MUSIC_E5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(476, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(477, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(478, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(479, PXA_MUSIC_E5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(480, PXA_MUSIC_F6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(480, PXA_MUSIC_A4, 7, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(480, PXA_MUSIC_B2, 8, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(480, PXA_MUSIC_D5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(480, PXA_MUSIC_F5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(481, PXA_MUSIC_D6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(482, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(483, PXA_MUSIC_F5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(484, PXA_MUSIC_F6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(485, PXA_MUSIC_D6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(486, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(487, PXA_MUSIC_F5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(487, PXA_MUSIC_C5, 1, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(488, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(488, PXA_MUSIC_E5, 8, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(488, PXA_MUSIC_C3, 8, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(488, PXA_MUSIC_A4, 8, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(488, PXA_MUSIC_E5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(489, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(490, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(491, PXA_MUSIC_E5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(492, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(493, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(494, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(495, PXA_MUSIC_E5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(496, PXA_MUSIC_F6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(496, PXA_MUSIC_A5, 8, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(496, PXA_MUSIC_D3, 8, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(496, PXA_MUSIC_D5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(496, PXA_MUSIC_F5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(497, PXA_MUSIC_D6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(498, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(499, PXA_MUSIC_F5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(500, PXA_MUSIC_F6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(501, PXA_MUSIC_D6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(502, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(503, PXA_MUSIC_F5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(504, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(504, PXA_MUSIC_E4, 8, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(504, PXA_MUSIC_A2, 8, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(504, PXA_MUSIC_A4, 8, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(504, PXA_MUSIC_E5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(505, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(506, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(507, PXA_MUSIC_E5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(508, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(509, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(510, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(511, PXA_MUSIC_E5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(512, PXA_MUSIC_F6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(512, PXA_MUSIC_A4, 7, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(512, PXA_MUSIC_B2, 8, 52, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(512, PXA_MUSIC_D5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(512, PXA_MUSIC_F5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(513, PXA_MUSIC_D6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(514, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(515, PXA_MUSIC_F5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(516, PXA_MUSIC_F6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(517, PXA_MUSIC_D6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(518, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(519, PXA_MUSIC_F5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(519, PXA_MUSIC_C5, 1, 108, PXA_MUSIC_TIMBRE_SAX),
    PXA_MUSIC_EVENT(520, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(520, PXA_MUSIC_E5, 8, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(520, PXA_MUSIC_C3, 8, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(520, PXA_MUSIC_A4, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(520, PXA_MUSIC_E5, 8, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(521, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(522, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(523, PXA_MUSIC_E5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(524, PXA_MUSIC_E6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(525, PXA_MUSIC_C6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(526, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(527, PXA_MUSIC_E5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(528, PXA_MUSIC_F6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(528, PXA_MUSIC_A5, 10, 108, PXA_MUSIC_TIMBRE_SAX), PXA_MUSIC_EVENT(528, PXA_MUSIC_D3, 10, 52, PXA_MUSIC_TIMBRE_STRINGS),
    PXA_MUSIC_EVENT(528, PXA_MUSIC_D5, 10, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(528, PXA_MUSIC_F5, 10, 54, PXA_MUSIC_TIMBRE_STRINGS), PXA_MUSIC_EVENT(529, PXA_MUSIC_D6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(530, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(531, PXA_MUSIC_F5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(532, PXA_MUSIC_F6, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(533, PXA_MUSIC_D6, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(534, PXA_MUSIC_A5, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(535, PXA_MUSIC_F5, 1, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(536, PXA_MUSIC_A2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(538, PXA_MUSIC_DS4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(538, PXA_MUSIC_E3, 1, 82, PXA_MUSIC_TIMBRE_BASS),
    PXA_MUSIC_EVENT(539, PXA_MUSIC_E4, 1, 120, PXA_MUSIC_TIMBRE_PIANO), PXA_MUSIC_EVENT(539, PXA_MUSIC_A3, 1, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(540, PXA_MUSIC_A4, 2, 120, PXA_MUSIC_TIMBRE_PIANO),
    PXA_MUSIC_EVENT(542, PXA_MUSIC_E2, 2, 82, PXA_MUSIC_TIMBRE_BASS), PXA_MUSIC_EVENT(544, PXA_MUSIC_A2, 2, 82, PXA_MUSIC_TIMBRE_BASS),
};

/* Alouette: traditional bird song, including verse and refrain. */
static const pxa_game_music_note_t pxa_game_music_flappy[] = {
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 3), PXA_MUSIC_NOTE(PXA_MUSIC_A4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_B4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_D4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 3), PXA_MUSIC_NOTE(PXA_MUSIC_A4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_B4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 4), PXA_MUSIC_NOTE(PXA_MUSIC_REST, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_D5, 2), PXA_MUSIC_NOTE(PXA_MUSIC_D5, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_E5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D5, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_D5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D5, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_D5, 2), PXA_MUSIC_NOTE(PXA_MUSIC_D4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_D4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_D5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D5, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_D5, 2), PXA_MUSIC_NOTE(PXA_MUSIC_D4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_D4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_D5, 2), PXA_MUSIC_NOTE(PXA_MUSIC_C5, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_B4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_A4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 4), PXA_MUSIC_NOTE(PXA_MUSIC_REST, 2),
};

/* She'll Be Coming 'Round the Mountain: a springy climbing arrangement. */
static const pxa_game_music_note_t pxa_game_music_jumping[] = {
    PXA_MUSIC_NOTE(PXA_MUSIC_C4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_E4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_E4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_C4, 4), PXA_MUSIC_NOTE(PXA_MUSIC_REST, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_C4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_E4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_E4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_C4, 4), PXA_MUSIC_NOTE(PXA_MUSIC_REST, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_E4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_E4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_F4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_A4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_F4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_E4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_D4, 4), PXA_MUSIC_NOTE(PXA_MUSIC_REST, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 2), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_E4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_F4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_E4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_C4, 4), PXA_MUSIC_NOTE(PXA_MUSIC_REST, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 2), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_E4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_F4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_E4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_C4, 6), PXA_MUSIC_NOTE(PXA_MUSIC_REST, 2),
};

/* Pop Goes the Weasel: compound-meter phrasing suits charge and release. */
static const pxa_game_music_note_t pxa_game_music_jump_jump[] = {
    PXA_MUSIC_NOTE(PXA_MUSIC_C4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_C4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_D4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_D4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_E4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_E4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_C4, 3),
    PXA_MUSIC_NOTE(PXA_MUSIC_C4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_C4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_D4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_D4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_E4, 3), PXA_MUSIC_NOTE(PXA_MUSIC_C4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_REST, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_C4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_C4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_D4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_D4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_E4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_E4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_C4, 3),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_REST, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_D4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_F4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_E4, 3), PXA_MUSIC_NOTE(PXA_MUSIC_C4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_REST, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_F4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_E4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_C4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_E4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_D4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_C4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_C4, 4), PXA_MUSIC_NOTE(PXA_MUSIC_REST, 2),
};

/* Yankee Doodle: a bright marching theme for the plane shooter. */
static const pxa_game_music_note_t pxa_game_music_plane[] = {
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 4),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_FS4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 4),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 2), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_FS4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_E4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_FS4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 4),
    PXA_MUSIC_NOTE(PXA_MUSIC_E4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_E4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_FS4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_E4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_D4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_E4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_FS4, 4),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_E4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_C4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_B3, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_A3, 4),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 2), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_G4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_FS4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_E4, 1), PXA_MUSIC_NOTE(PXA_MUSIC_FS4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_G4, 5), PXA_MUSIC_NOTE(PXA_MUSIC_REST, 1),
};

/* Korobeiniki: both familiar strains rather than the former 16-note excerpt. */
static const pxa_game_music_note_t pxa_game_music_tetris[] = {
    PXA_MUSIC_NOTE(PXA_MUSIC_E5, 2), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D5, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_A4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_E5, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_D5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_C5, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_B4, 3), PXA_MUSIC_NOTE(PXA_MUSIC_C5, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_D5, 2), PXA_MUSIC_NOTE(PXA_MUSIC_E5, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 2), PXA_MUSIC_NOTE(PXA_MUSIC_A4, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 4),
    PXA_MUSIC_NOTE(PXA_MUSIC_D5, 3), PXA_MUSIC_NOTE(PXA_MUSIC_F5, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_A5, 2), PXA_MUSIC_NOTE(PXA_MUSIC_G5, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_F5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_E5, 3),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_E5, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_D5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_C5, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_B4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 1),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 1), PXA_MUSIC_NOTE(PXA_MUSIC_D5, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_E5, 2), PXA_MUSIC_NOTE(PXA_MUSIC_C5, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_A4, 2), PXA_MUSIC_NOTE(PXA_MUSIC_A4, 4),
    PXA_MUSIC_NOTE(PXA_MUSIC_E5, 4), PXA_MUSIC_NOTE(PXA_MUSIC_C5, 4),
    PXA_MUSIC_NOTE(PXA_MUSIC_D5, 4), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 4),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 4), PXA_MUSIC_NOTE(PXA_MUSIC_A4, 4),
    PXA_MUSIC_NOTE(PXA_MUSIC_GS4, 4), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 4),
    PXA_MUSIC_NOTE(PXA_MUSIC_E5, 4), PXA_MUSIC_NOTE(PXA_MUSIC_C5, 4),
    PXA_MUSIC_NOTE(PXA_MUSIC_D5, 4), PXA_MUSIC_NOTE(PXA_MUSIC_B4, 4),
    PXA_MUSIC_NOTE(PXA_MUSIC_C5, 2), PXA_MUSIC_NOTE(PXA_MUSIC_E5, 2),
    PXA_MUSIC_NOTE(PXA_MUSIC_A5, 4), PXA_MUSIC_NOTE(PXA_MUSIC_GS5, 8),
    PXA_MUSIC_NOTE(PXA_MUSIC_REST, 2),
};

static const pxa_game_music_song_t pxa_game_music_songs[PXA_GAME_SFX_THEME_COUNT] = {
    {pxa_game_music_brick, PXA_MUSIC_LENGTH(pxa_game_music_brick), 148,
     0x5555, 0x4444, 0xEEEE,
     {PXA_MUSIC_G3, PXA_MUSIC_D3, PXA_MUSIC_G3, PXA_MUSIC_D3,
      PXA_MUSIC_C3, PXA_MUSIC_G3, PXA_MUSIC_D3, PXA_MUSIC_G3},
     0, 0, 0},
    {pxa_game_music_garden, PXA_MUSIC_LENGTH(pxa_game_music_garden), 118,
     0, 0, 0,
     {PXA_MUSIC_REST, PXA_MUSIC_REST, PXA_MUSIC_REST, PXA_MUSIC_REST,
      PXA_MUSIC_REST, PXA_MUSIC_REST, PXA_MUSIC_REST, PXA_MUSIC_REST},
     pxa_game_music_garden_score, PXA_MUSIC_LENGTH(pxa_game_music_garden_score),
     546},
    {pxa_game_music_flappy, PXA_MUSIC_LENGTH(pxa_game_music_flappy), 120,
     0x1111, 0x4444, 0xAAAA,
     {PXA_MUSIC_G3, PXA_MUSIC_D3, PXA_MUSIC_G3, PXA_MUSIC_D3,
      PXA_MUSIC_C3, PXA_MUSIC_G3, PXA_MUSIC_D3, PXA_MUSIC_G3},
     0, 0, 0},
    {pxa_game_music_jumping, PXA_MUSIC_LENGTH(pxa_game_music_jumping), 132,
     0x1111, 0x4444, 0xEEEE,
     {PXA_MUSIC_C3, PXA_MUSIC_G3, PXA_MUSIC_C3, PXA_MUSIC_G3,
      PXA_MUSIC_F3, PXA_MUSIC_C3, PXA_MUSIC_G3, PXA_MUSIC_C3},
     0, 0, 0},
    {pxa_game_music_jump_jump, PXA_MUSIC_LENGTH(pxa_game_music_jump_jump), 128,
     0x1111, 0x4040, 0xAAAA,
     {PXA_MUSIC_C3, PXA_MUSIC_G3, PXA_MUSIC_C3, PXA_MUSIC_G3,
      PXA_MUSIC_F3, PXA_MUSIC_C3, PXA_MUSIC_G3, PXA_MUSIC_C3},
     0, 0, 0},
    {pxa_game_music_plane, PXA_MUSIC_LENGTH(pxa_game_music_plane), 144,
     0x1515, 0x4444, 0xEEEE,
     {PXA_MUSIC_G3, PXA_MUSIC_D3, PXA_MUSIC_G3, PXA_MUSIC_D3,
      PXA_MUSIC_C3, PXA_MUSIC_G3, PXA_MUSIC_D3, PXA_MUSIC_G3},
     0, 0, 0},
    {pxa_game_music_tetris, PXA_MUSIC_LENGTH(pxa_game_music_tetris), 144,
     0x1111, 0x4444, 0xAAAA,
     {PXA_MUSIC_A3, PXA_MUSIC_E3, PXA_MUSIC_A3, PXA_MUSIC_E3,
      PXA_MUSIC_D3, PXA_MUSIC_A3, PXA_MUSIC_E3, PXA_MUSIC_A3},
     0, 0, 0},
};

static inline const pxa_game_music_song_t* pxa_game_music_song(uint8_t theme) {
    return &pxa_game_music_songs[theme < PXA_GAME_SFX_THEME_COUNT ? theme :
                                 PXA_GAME_SFX_THEME_BRICK];
}

#endif
